---
new_page_extension: md
auto_deploy: false
admin_path: ""
webhook_url:
sections:
  - type: heading
    label: Config
  - type: document
    path: content/data/services
    label: Services
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
      - service
  - type: document
    path: content/data/packages
    label: Packages
    create: documents
    match: "**/*"
    new_doc_ext: md
    templates:
      - package
upload_dir: content/images
public_path: content/images
front_matter_path: ""
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
